# To run: conda env create -f environment.yml
name: nerf
channels:
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - cudatoolkit=10.0
    - numpy
    - matplotlib
    - imageio
    - imageio-ffmpeg
    - configargparse
    - chardet
    - scipy